site_name: MassiPipe Documentation
site_description: MassiPipe - a data processing pipeline for hyperspectral data acquired in the Massimal project.

theme:
  name: "material"
  features:
    - content.code.copy

repo_url: https://github.com/mh-skjelvareid/massipipe

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: true
          members_order: source
          heading_level: 2
          show_root_heading: false
          show_source: false
          show_signature: true

nav:
  - Introduction: index.md
  - Pipeline reference: pipeline_ref.md
  - Processors reference: processors_ref.md
  - Utilities reference: utils_ref.md
  - Example Usage: example_usage.md

markdown_extensions:
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences